#!/usr/bin/env bash
# Regenerate internal/worker/builtin/cursor_models.go from the cursor-agent
# binary's own catalog.
#
# cursor-agent exposes 200+ model ids and folds the effort axis into the id, so
# the list is far too large and too fast-moving to hand-maintain: it is a
# snapshot, refreshed by running this script against an installed, logged-in
# cursor-agent. Unit tests pin the listing format and catalog-diff rules against
# fixtures; they do not shell out to cursor-agent.
#
# Entries are sorted by id: cursor-agent prints its catalog in an unstable
# order, and an unsorted snapshot would churn the whole file on every refresh.
#
# Usage: scripts/gen-cursor-models.sh
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
out="$repo_root/internal/worker/builtin/cursor_models.go"

if ! command -v cursor-agent >/dev/null 2>&1; then
  echo "gen-cursor-models: cursor-agent is not on PATH" >&2
  exit 1
fi

version=$(cursor-agent --version 2>/dev/null | head -1)
listing=$(cursor-agent --list-models)

# Body lines are "<id> - <label>"; the header and the trailing tip line are not.
entries=$(printf '%s\n' "$listing" | awk -F ' - ' '
  NF < 2 { next }
  $1 ~ /[[:space:]]/ { next }
  $1 == "" || $2 == "" { next }
  { printf "\t{ID: %s, Label: %s},\n", "\"" $1 "\"", "\"" $2 "\"" }
' | LC_ALL=C sort)

if [ -z "$entries" ]; then
  echo "gen-cursor-models: cursor-agent --list-models produced no entries (logged in?)" >&2
  exit 1
fi

{
  echo "// Code generated by scripts/gen-cursor-models.sh. DO NOT EDIT."
  echo "//"
  echo "// Source: \`cursor-agent --list-models\` (cursor-agent ${version})."
  echo "//"
  echo "// Effort is part of the id here, not a separate flag: -low/-medium/-high/"
  echo "// -xhigh/-max suffixes, with an orthogonal -fast variant. See"
  echo "// cursorModelOption in cursor.go."
  echo
  echo "package builtin"
  echo
  echo "// cursorModels is the cursor-agent model catalog snapshot."
  echo "var cursorModels = []cursorModel{"
  printf '%s' "$entries"
  echo "}"
} >"$out"

gofmt -w "$out"
echo "gen-cursor-models: wrote $(grep -c '{ID:' "$out") ids to $out"
